name: Build and test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install GCC & GDB & other build essentials
        run: |
          sudo apt-get -y install build-essential gcc g++ gdb gdbserver
          gdb --version
          gcc --version
          gdbserver --version
      - name: Build
        run: yarn
      - name: Test
        run: yarn test-ci
      - name: Log file artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: test-logs/
      - name: Test Reporter
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure()
        with:
          name: Integration Tests
          path: test-reports/*.xml
          reporter: java-junit
          max-annotations: '0'
          fail-on-error: 'true'
